print("# 하나만 출력합니다.")
print("Hello Python Programming ...!")
print()

print("여러 개를 출력합니다.")
print(10,20,30,40,50)
print("안녕하세요","저의","이름은","최현우 입니다.")
print()

print("#아무것도 출력하지 않았습니다.")
print("--확인 전용선--")
print()
print()
print("--확인 전용선--")


print("\"안녕하세요\"라고 말했습니다")
print('\'배가 고픕니다\'라고 생각했습니다')
print("안녕하세요\n안녕하세요")
print("안녕하세요\t안녕하세요")

print("문자 선택 연산자에 대해 알아볼까요?")
print("안녕하세요"[0])
print("안녕하세요"[1])
print("안녕하세요"[2])
print("안녕하세요"[3])
print("안녕하세요"[4])
print("")
print("안녕하세요"[-1])
print("안녕하세요"[-2])
print("안녕하세요"[-3])
print("안녕하세요"[-4])
print("안녕하세요"[-5])
print("안녕하세요"[1:4])
print("\\"*8)

print("5+7 =",5+7)
print("5-7 =",5-7)
print("5*7 = ",5*7)
print("5/7 =",5/7)
print("5//2 =",5//2)
print("5%2 =",5/2)
